name: build-push-jumanpp-knp-kwja

# DO NOT trigger on pull requests for security reasons
on:
  schedule:
    - cron: '0 20 1 * *'  # Runs at 20:00 UTC on the 1st of every month.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

env:
  registry-user: kunlp
  kwja-version: 2.5.0

jobs:
  build-push-jumanpp:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        base-image: ["ubuntu:22.04", "ubuntu:24.04", "ubuntu:26.04", "debian:trixie"]
        include:
          - base-image: "ubuntu:22.04"
            tag: "ubuntu22.04"
          - base-image: "ubuntu:24.04"
            tag: "ubuntu24.04"
          - base-image: "ubuntu:26.04"
            tag: "ubuntu26.04"
          - base-image: "debian:trixie"
            tag: "debian13"
    steps:
      - name: Generate tags
        id: generate-tags
        # jumanpp:latest is excluded because there is another alpine-based image
        run: |
          tag_prefix="${{ env.registry-user }}/jumanpp"
          tags="${tag_prefix}:${{ matrix.tag }}"
          if [[ ${{ matrix.base-image }} == 'ubuntu:26.04' ]]; then
            tags+=",${tag_prefix}:ubuntu"
          fi
          echo "tags=${tags}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v7
      - uses: ./.github/actions/build-push-image
        with:
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: jumanpp.dockerfile
          cache-scope: jumanpp-${{ matrix.tag }}
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
          tags: ${{ steps.generate-tags.outputs.tags }}

  build-push-kwja:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        base-image: ["ubuntu:22.04", "ubuntu:24.04", "ubuntu:26.04", "debian:trixie"]
        include:
          - base-image: "ubuntu:22.04"
            tag: "ubuntu22.04"
          - base-image: "ubuntu:24.04"
            tag: "ubuntu24.04"
          - base-image: "ubuntu:26.04"
            tag: "ubuntu26.04"
          - base-image: "debian:trixie"
            tag: "debian13"
    steps:
      - name: Generate tags
        id: generate-tags
        run: |
          tag_prefix="${{ env.registry-user }}/kwja"
          tags="${tag_prefix}:${{ matrix.tag }}"
          if [[ ${{ matrix.base-image }} == 'ubuntu:26.04' ]]; then
            tags+=",${tag_prefix}:ubuntu,${tag_prefix}:latest"
          fi
          echo "tags=${tags}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v7
      - uses: ./.github/actions/build-push-image
        with:
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: kwja.dockerfile
          cache-scope: kwja-${{ matrix.tag }}
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
            KWJA_VERSION=${{ env.kwja-version }}
          tags: ${{ steps.generate-tags.outputs.tags }}

  build-push-jumanpp-knp:
    needs: build-push-jumanpp
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        base-image: ["ubuntu:22.04", "ubuntu:24.04", "ubuntu:26.04"]
        include:
          - base-image: "ubuntu:22.04"
            tag: "ubuntu22.04"
          - base-image: "ubuntu:24.04"
            tag: "ubuntu24.04"
          - base-image: "ubuntu:26.04"
            tag: "ubuntu26.04"
    steps:
      - id: generate-tags
        run: |
          tag_prefix="${{ env.registry-user }}/jumanpp-knp"
          tags="${tag_prefix}:${{ matrix.tag }}"
          if [[ ${{ matrix.base-image }} == 'ubuntu:26.04' ]]; then
            tags+=",${tag_prefix}:ubuntu,${tag_prefix}:latest"
          fi
          echo "tags=${tags}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v7
      - uses: ./.github/actions/build-push-image
        with:
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: jumanpp-knp.dockerfile
          cache-scope: jumanpp-knp-${{ matrix.tag }}
          build-args: |
            BASE_IMAGE_JUMANPP=${{ env.registry-user }}/jumanpp:${{ matrix.tag }}
            BASE_IMAGE=${{ matrix.base-image }}
          tags: ${{ steps.generate-tags.outputs.tags }}

  build-push-jumanpp-kwja:
    needs: [build-push-jumanpp, build-push-kwja]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        base-image: ["ubuntu:22.04", "ubuntu:24.04", "ubuntu:26.04"]
        include:
          - base-image: "ubuntu:22.04"
            tag: "ubuntu22.04"
          - base-image: "ubuntu:24.04"
            tag: "ubuntu24.04"
          - base-image: "ubuntu:26.04"
            tag: "ubuntu26.04"
    steps:
      - id: generate-tags
        run: |
          tag_prefix="${{ env.registry-user }}/jumanpp-kwja"
          tags="${tag_prefix}:${{ matrix.tag }}"
          if [[ ${{ matrix.base-image }} == 'ubuntu:26.04' ]]; then
            tags+=",${tag_prefix}:ubuntu,${tag_prefix}:latest"
          fi
          echo "tags=${tags}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v7
      - uses: ./.github/actions/build-push-image
        with:
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: jumanpp-kwja.dockerfile
          cache-scope: jumanpp-kwja-${{ matrix.tag }}
          build-args: |
            BASE_IMAGE_JUMANPP=${{ env.registry-user }}/jumanpp:${{ matrix.tag }}
            BASE_IMAGE_KWJA=${{ env.registry-user }}/kwja:${{ matrix.tag }}
          tags: ${{ steps.generate-tags.outputs.tags }}

  build-push-jumanpp-knp-kwja:
    needs: [build-push-jumanpp-knp, build-push-kwja]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        base-image: ["ubuntu:22.04", "ubuntu:24.04", "ubuntu:26.04"]
        include:
          - base-image: "ubuntu:22.04"
            tag: "ubuntu22.04"
          - base-image: "ubuntu:24.04"
            tag: "ubuntu24.04"
          - base-image: "ubuntu:26.04"
            tag: "ubuntu26.04"
    steps:
      - id: generate-tags
        run: |
          tag_prefix="${{ env.registry-user }}/jumanpp-knp-kwja"
          tags="${tag_prefix}:${{ matrix.tag }}"
          if [[ ${{ matrix.base-image }} == 'ubuntu:26.04' ]]; then
            tags+=",${tag_prefix}:ubuntu,${tag_prefix}:latest"
          fi
          echo "tags=${tags}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v7
      - uses: ./.github/actions/build-push-image
        with:
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: jumanpp-knp-kwja.dockerfile
          cache-scope: jumanpp-knp-kwja-${{ matrix.tag }}
          build-args: |
            BASE_IMAGE_JUMANPP_KNP=${{ env.registry-user }}/jumanpp-knp:${{ matrix.tag }}
            BASE_IMAGE_KWJA=${{ env.registry-user }}/kwja:${{ matrix.tag }}
          tags: ${{ steps.generate-tags.outputs.tags }}
